# Generated by Django 4.1.6 on 2023-03-15 18:02

from django.db import migrations, models
import main.shared.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_referral_proposal_profile_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creation_time',
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.shared.utils.SkillTreeUtils.get_profile_user_file_path),
        ),
    ]
