# Generated by Django 4.1.6 on 2023-03-15 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='count_of_requested_tasks',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='count_of_served_tasks',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('BUSY', 'Busy'), ('FREE', 'Free')], max_length=20, null=True),
        ),
    ]
