# Generated by Django 4.1.6 on 2023-03-20 15:59

from django.db import migrations, models
import main.shared.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_count_of_requested_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=main.shared.utils.SkillTreeUtils.get_task_attachments_file_path),
        ),
    ]
