# Generated by Django 4.1.6 on 2023-03-26 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='client',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rate', to=settings.AUTH_USER_MODEL),
        ),
    ]
