# Generated by Django 4.1.6 on 2023-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_rate_client_remove_rate_freelancer_rate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='skill',
        ),
    ]
