# Generated by Django 4.1.6 on 2023-03-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_faqentity_remove_certificate_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQEntity',
            new_name='FAQ',
        ),
    ]
