# Generated by Django 4.1.6 on 2023-03-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_faqentity_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('FREELANCER', 'Freelancer')], max_length=20, null=True),
        ),
    ]
